### ISSUE TITLE
post not working with fusion

### ISSUE THREAD

**Issue by rbaertsch** [UCSC-MedBook/MedBook-Fusion5#1]
The pop-up window is blank that should show the post information.   l
When I click post on medbook.ucsc.edu, the popup window is blank. Below is javascript console errors

About to init Collaboration

cf499a4….js:3 Exception in callback of async function: Error: Handler with name 'u' already exists.
   at i._create (https://medbook.ucsc.edu/cf499a4de6fa44dd63c0631e44a3f2cd9d47ac0a.js:110:1577)
   at i.push (https://medbook.ucsc.edu/cf499a4de6fa44dd63c0631e44a3f2cd9d47ac0a.js:110:1761)
   at https://medbook.ucsc.edu/cf499a4de6fa44dd63c0631e44a3f2cd9d47ac0a.js:110:2011
   at Array.forEach (native)
   at Function.A.each.A.forEach (https://medbook.ucsc.edu/cf499a4de6fa44dd63c0631e44a3f2cd9d47ac0a.js:1:865)
   at i.append (https://medbook.ucsc.edu/cf499a4de6fa44dd63c0631e44a3f2cd9d47ac0a.js:110:1941)
   at https://medbook.ucsc.edu/cf499a4de6fa44dd63c0631e44a3f2cd9d47ac0a.js:110:2130
   at Array.forEach (native)
   at Function.A.each.A.forEach (https://medbook.ucsc.edu/cf499a4de6fa44dd63c0631e44a3f2cd9d47ac0a.js:1:865)
   at i.append (https://medbook.ucsc.edu/cf499a4de6fa44dd63c0631e44a3f2cd9d47ac0a.js:110:1941)

**Comment by tedgoldstein** [comment]
I was just able to post from Fusion to  MedBook.ucsc.edu.

I don't see this happening.

pop-up window is blank that should show the post information.   l

About to init Collaboration

cf499a4….js:3 Exception in callback of async function: Error: Handler with name 'u' already exists.
